site_name: starfinder

nav:
  - 'index.md'
  - 'installation.md'
  - Getting started: notebooks/getting_started.ipynb
  - Estimating the background: notebooks/background.ipynb
  - Clustering: notebooks/clustering.ipynb

plugins:
  - mkdocs-autoapi
  - mkdocstrings
  - mkdocs-jupyter

theme:
  name: "material"
