site_name: starfinder

nav:
  - 'index.md'
  - 'installation.md'
  - Getting started: notebooks/Getting_started.ipynb

plugins:
  - mkdocs-autoapi
  - mkdocstrings
  - mkdocs-jupyter

theme:
  name: "material"
