[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "starfinder"
authors = [{name = "Glen Cowan"}]
dynamic = ["version", "description"]
